#!/bin/bash

for pomFile in ./jars/*/pom.xml; do
    artifact=$(basename $(dirname $pomFile))
    echo "Installing $artifact..."
    jarFile=./jars/$artifact-1.3.2.jar
    mvn install:install-file -Dfile=$jarFile -DpomFile=$pomFile
done
